icons-osama
VBDojnaz/lucky-duck pull request #5
Opened 2022-10-14 23:21 UTC by osamakamelju

Som första steg har jag lagt till ikoner (grisen inte visas jag vet inte varför).

2022-10-15 21:10 UTC, VBDojnaz requested changes
The protein selector should be floating, not docked to the bottom of the screen.

2022-10-15 21:10 UTC, VBDojnaz commented on index.html
> +    <script src="https://kit.fontawesome.com/be13722f69.js" crossorigin="anonymous"></script>
Please use `<script src="https://kit.fontawesome.com/dd99507b81.js" crossorigin="anonymous"></script>` as it fixes the issue of some icons not showing (premium icons)

2022-10-18 22:50 UTC, VBDojnaz approved these changes

2022-10-19 12:15 UTC, dshertz approved these changes

2022-10-19 16:26 UTC, MaramTahan approved these changes

2022-10-20 19:37 UTC, VBDojnaz commented
Koden är direkt i #9 istället.

2022-10-20 19:37 UTC, closed without merging