Daniel navigation allergier filtrering
VBDojnaz/lucky-duck pull request #7
Opened 2022-10-17 11:10 UTC by dshertz

Topbar är redo för reviews och tankar

2022-10-17 15:24 UTC, VBDojnaz requested changes

2022-10-17 15:24 UTC, VeeBack commented on index.html
> + <link rel="stylesheet" href="/daniel-topnav.css">
Lägg till detta scriptet `<script src="https://kit.fontawesome.com/dd99507b81.js" crossorigin="anonymous"></script>`

2022-10-17 15:24 UTC, VBDojnaz commented on index.html
> +            <img onclick="toggleShowHide('navbar-barley')" id="navbar-barley" class="hide" src="/img/barley.png" alt="">
Istället för att använda bilder, kan du använda detta: `<i class="fa-solid fa-wheat"></i>`

2022-10-18 08:18 UTC, dshertz commented on index.html
> + <link rel="stylesheet" href="/daniel-topnav.css">
fixat

2022-10-18 08:18 UTC, dshertz commented on index.html
> +            <img onclick="toggleShowHide('navbar-barley')" id="navbar-barley" class="hide" src="/img/barley.png" alt="">
fixat

2022-10-18 12:22 UTC, VBDojnaz approved these changes
Looks great!

2022-10-18 15:50 UTC, MaramTahan approved these changes

2022-10-18 15:51 UTC, merged